<a href="https://colab.research.google.com/github/AncientHearings/Data-Science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np #Import all the functions into the currently running maion programme.

In [3]:
from numpy import *

####Creating Arrays


In [4]:
#array() function is used to create one, two snd three dimensionalmatrix.
#ones()
#zeros()
#empty

arr1 = array([1, 2])
arr1

array([1, 2])

In [6]:
arr2 = array([[1, 2], [3, 4]])
arr2

array([[1, 2],
       [3, 4]])

In [8]:
arr3 = ones((2, 3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr4= zeros((2, 3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr5 = empty((2, 2))
arr5

array([[1.29081364e-315, 0.00000000e+000],
       [5.38670379e+228, 2.47085366e-259]])

####Ranges  
  
linespace() and arange()

In [11]:
arr6 = arange(1, 50, 2)
arr6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [12]:
arr7 = linspace(0, 1, 5)
arr7

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

####Special Arrays  
  
eye()  
diag()  
random.rand()

In [13]:
identity = eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
diagonal = diag([1, 2, 3])
diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
random = random.rand(1, 4)
random

array([[0.91208542, 0.97971287, 0.21878468, 0.75394228]])

####Array Properties


ndim  
size  
shape  
dtype

In [16]:
arr7.ndim

1

In [17]:
arr7.shape

(5,)

In [18]:
arr7.size

5

In [20]:
arr7.dtype

dtype('float64')

####Basic Operations

Arithmetic Operations

In [22]:
a = array([1, 2, 3])
b = array([4, 5, 6])
print(a +b)

[5 7 9]


Aggregate Functions

In [23]:
sum(a)

np.int64(6)

In [24]:
mean(a)

np.float64(2.0)

In [25]:
max(a)

np.int64(3)

####Indexing and Slicing

1D array

In [26]:
arr = array([1, 2, 3, 4, 5, 6])
arr[0]

np.int64(1)

In [27]:
arr[0:4]

array([1, 2, 3, 4])

2D array

In [28]:
arr = array([[1, 2, 3], [4, 5, 6]])
arr[0, 0]

np.int64(1)

In [29]:
arr[:, 1]

array([2, 5])

####Practice

In [30]:
#1. Create a 3 x 3 array of zeros
arr = zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
#2. Generate an array of even numbers from 0 to 10
arr = arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [34]:
#Compute the mean of [5, 10, 15]
sum([5, 10, 15])

np.int64(30)

#Advanced NumPy Operations

##Reshaping and Combining Arrays

In [35]:
#RESHAPING ARRAYS
#Change array dimensions without altering data

arr = arange(6)
arr = reshape(arr, (2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
#Flatten Arrays
arr = array([[1, 2], [3, 4]])
arr = arr.ravel() #Doesn't create copy. Only for viewing
arr

array([1, 2, 3, 4])

In [39]:
#Stacking Arrays
a = array([1, 2])
b = array([3, 4])

v_stack = vstack((a, b))
v_stack

array([[1, 2],
       [3, 4]])

In [40]:
h_stack = hstack((a, b))
h_stack

array([1, 2, 3, 4])

##BROADCASTING

In [41]:
a = array([[1, 2], [3, 4]]) # 2 x 2
b = array([1, 2])           # 1 x 2
c = a + b
c

array([[2, 4],
       [4, 6]])

Both dimension should be same or atleast one should be 1.  
  
ALigns trailing dimensions

##Universal Functions(ufunc)

##Linear Algebra

In [42]:
#Matrix Multiplication
a = array([[1, 2], [3, 4]])
b = array([[5, 6], [7, 8]])
DotProduct = dot(a, b)
DotProduct

array([[19, 22],
       [43, 50]])

In [44]:
#Inverse and Determinant
matrix = array([[1, 2], [3, 4]])

inv_matrix = linalg.inv(matrix)
inv_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
Determinant = linalg.det(matrix)
Determinant

np.float64(-2.0000000000000004)

##Boolean Masking

Filter arrays using condition

In [46]:
arr = array([1, 2, 3, 4,])
mask = arr > 2
arr = arr[mask]
arr

array([3, 4])

In [48]:
arr = arr[arr % 2 == 0]
arr

array([4])

##Random Module

Generate random data

In [50]:
rand_arr = np.random.rand(1, 2)
rand_arr

array([[0.19703051, 0.67575549]])

In [51]:
norm_arr = np.random.randn(3)
norm_arr

array([-0.46367709, -0.16597073,  1.0341253 ])

In [52]:
int_rand = np.random.randint(1, 5)
int_rand

3

##Practice

In [54]:
#Reshape np.arange(9) into a 3 x 3 matrix
arr = np.arange(9)
arr = arr.reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
from numpy import *

In [58]:
#Multiply a 2 x 3 matrix by a 3 x1 vector

a = ones((2, 3))
b = ones((1, 3))

c = a + b
c

array([[2., 2., 2.],
       [2., 2., 2.]])

In [60]:
#Extract all values > 5 from np.array([2, 6, 1, 8, 3])

a = array([2, 6, 1, 8, 3])
mask = a > 5
a = a[mask]
a

array([6, 8])