<a href="https://colab.research.google.com/github/AncientHearings/Data-Science/blob/main/NumpyArrayDimensionsDay4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as x#importing numpy library
#Numpy library is for mathematical problems.
#Linear Algebra Problems
#Matrix Problems
#Calculus Problems.
#Array Dimensions
#One dimensional
#two dimensional
#three dimensional


In [7]:
A=x.array(5)#Scalar army
print(A)

5


In [5]:
x.ndim(A)#Dimension method

0

0

In [8]:
one=x.array([1,2,3,4,5])#1D array
print(one)
x.ndim(one)

[1 2 3 4 5]


1

In [10]:
two=x.array([[1,2,3],[4,5,6]])#2D array
print(two)
x.ndim(two)#Dimenison method

[[1 2 3]
 [4 5 6]]


2

In [11]:
three=x.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#3d array
#array () function is used to create 1-,2- or 3-D array
#array() function is associated with numpy library.
#Arguments passed to it.
print(three)
x.ndim(three)#Dimenison method

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

List vs Numpy Array

In [ ]:
list=[1,2,0,'apple']#Different datatypes
arr=x.array[1,2,3]#same data type


In [17]:
one=x.array([1,2,3,4,5])#One dimensional array
print(one)
x.ndim(one)
one/5#Mathematical operations can be performed on array.



[1 2 3 4 5]


array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#Array consumes less memory
#Array is faster than list .